version: '3.8'

services:
  frontend:
    image: ${DOCKER_REGISTRY}exam-planner-frontend:${IMAGE_TAG:-latest}
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    image: ${DOCKER_REGISTRY}exam-planner-backend:${IMAGE_TAG:-latest}
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/exam-study-planner
      - PORT=5001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: